# Generated by Django 4.2.4 on 2023-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio_calculator', '0004_riskscore_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='hdl_cholesterol',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='total_cholesterol',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
